server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: product-service
        uri: lb://product-service
        predicates:
        - Path=/products/**
      - id: offer-service
        uri: lb://offer-service
        predicates:
        - Path=/offers/**
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/users/**
      - id: notification-service
        uri: lb://notification-service
        predicates:
        - Path=/notifications/**