spring:
  application:
    name: offer-service
  cloud:
    stream:
      bindings:
        output:
          destination: offer-event
server:
  port: 9002

---

spring:
  profiles: dev
  data:
    mongodb:
      host: offers-db